name: search_points
description: A Dart package offering multiple search algorithms including Linear, Binary, and Jump Search. Useful for performance comparisons and algorithmic analysis in Dart libraries and applications.

version: 1.0.0
repository: https://github.com/Tursunali008/search_points

environment:
  sdk: ^3.4.4

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
license: MIT